name: CONTINUOUS DELIVERY AND DEPLOYMENT

on:
  push:
    branches:
      - main

jobs:
  Lint-and-Test:
    name: Lint and Test Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'
      - name: Install Dependencies
        run: npm ci

      - name: Format The Code Base
        run: npm run format
      - name: Run Lint Command
        run: npm run lint
  Build-and-Push:
    name: Build and Push Docker Image
    needs: [Lint-and-Test]
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Login In To Docker
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build The Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            abdullah00001/gadgetbajar:${{github.ref_name}}
            abdullah00001/gadgetbajar:latest
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
